env: python
envVersion: 3.11.1

services:
  - type: web
    name: luffalense
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn luffa_prediction.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 300
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "luffalense.onrender.com"
      - key: DJANGO_SECRET_KEY
        generateValue: true
    autoDeploy: true

  - type: pserv
    name: luffalense
    runtime: postgres
